    obstacle_range: 2.5
    raytrace_range: 3.0
    foorprint: [[0.273, 0.123], [0.273, -0.123], [-0.273,-0.123], [-0.273, 0.123]]
    inflation_radius: 0.15
    max_obstacle_height: 10.0
    min_obstacle_height: 0.0
    observation_sources: scan
    scan: {daya_type: LaserScan, topic: /scan, marketing: true, clearing: true, expected_update_rate: 0}
